name: flutter_offline_data_sync
version: 1.0.0
description: A Flutter package for offline data synchronization with local storage and automatic retry.
repository: https://github.com/Yashil07/flutter_offline_data_sync
homepage: https://github.com/Yashil07/flutter_offline_data_sync


environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.3
  path_provider: ^2.0.11
  uuid: ^4.5.1
  dio: ^5.3.2
  sqflite: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3